# Generated by Django 5.2.1 on 2025-06-02 02:31

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='user_images/')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_account', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20, unique=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logo/')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_status', models.CharField(choices=[('client', 'client'), ('agent', 'agent')], default='client', editable=False, max_length=10)),
            ],
            options={
                'verbose_name': 'Клиент/Владелец',
                'verbose_name_plural': 'Клиенты/Владельцы',
            },
            bases=('izde_app.userprofile',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_apartment', models.TextField(max_length=500)),
                ('address', models.CharField(max_length=100)),
                ('for_buy_or_rent', models.CharField(choices=[('buy', 'buy'), ('rent', 'rent')], default='rent')),
                ('count_bathroom', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('count_bedroom', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('bathroom', models.CharField(choices=[('combined', 'combined'), ('separate', 'separate')])),
                ('minimum_stay', models.DateField()),
                ('deposit', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999999)])),
                ('price', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999999)])),
                ('square', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)])),
                ('apartment_type', models.CharField(choices=[('apartment', 'apartment'), ('townhouse', 'townhouse'), ('penthouse', 'penthouse'), ('office', 'office')])),
                ('number_of_room', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)])),
                ('floor', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('floor_of', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('type_of_parking', models.CharField(choices=[('ground', 'ground'), ('underground', 'underground'), ('no', 'no')])),
                ('amenities', multiselectfield.db.fields.MultiSelectField(choices=[('smoking_in_the_apartment', 'smoking_in_the_apartment'), ('listen_to_music_loudly', 'listen_to_music_loudly'), ('balkony', 'balkony'), ('microwave', 'microwave'), ('wifi', 'wifi'), ('central_heating', 'central_heating'), ('tv', 'tv'), ('washing_machine', 'washing_machine'), ('air_conditioner', 'air_conditioner'), ('tableware', 'tableware'), ('swimming_pool', 'swimming_pool'), ('gym', 'gym'), ('workspace', 'workspace'), ('pet_friendly', 'pet_friendly')], max_length=200)),
                ('created_by', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='izde_app.city')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='izde_app.home')),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_image', models.ImageField(blank=True, null=True, upload_to='apartment_images/')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_image', to='izde_app.apartment')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='izde_app.apartment')),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='izde_app.favorite')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_review', models.TextField()),
                ('stars', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='izde_app.apartment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='izde_app.apartment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_status', models.CharField(choices=[('client', 'client'), ('agent', 'agent')], default='agent', editable=False, max_length=10)),
                ('languages', multiselectfield.db.fields.MultiSelectField(choices=[('English', 'English'), ('Russian', 'Russian'), ('Kyrgyz', 'Kyrgyz')], max_length=22)),
                ('experience_since', models.DateField()),
                ('position', models.CharField(choices=[('expert', 'expert'), ('junior', 'junior')], default='expert', max_length=20)),
                ('areas_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='izde_app.city')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='izde_app.company')),
            ],
            options={
                'verbose_name': 'Агент',
                'verbose_name_plural': 'Агенты',
            },
            bases=('izde_app.userprofile',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
